# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: timbru31/java-node

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - apt-get update
            # Install latest chrome dev package, which installs the necessary libs to
          # make the bundled version of Chromium that Puppeteer installs work.
          - apt-get install -y wget --no-install-recommends
          - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
          - sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
          - apt-get update
          - apt-get install -y google-chrome-unstable --no-install-recommends
          - rm -rf /var/lib/apt/lists/*
          - wget --quiet https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh -O /usr/sbin/wait-for-it.sh
          - chmod +x /usr/sbin/wait-for-it.sh
          - npm install
          - runTestCommand
