name: Run Tests

on: [push]

env:
  CI: true
  # Force terminal colors. @see https://www.npmjs.com/package/colors
  FORCE_COLOR: 1

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js nodeVersion
        uses: actions/setup-node@v1
        with:
          node-version: nodeVersion
      - name: Install deps
        run: npm i
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: true
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
      - name: Run Tests
        run: runTestCommand
